# Generated by Django 3.0.6 on 2020-06-03 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=15, unique=True)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('transactionAmount', models.BigIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('transactionFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debited', to=settings.AUTH_USER_MODEL)),
                ('transactionTo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='credited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=3000)),
                ('accountNumber', models.CharField(default='0123456789', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintID', models.CharField(max_length=15, unique=True)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=180)),
                ('complaintUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Transaction')),
            ],
        ),
    ]
