# Generated by Django 3.0.6 on 2020-05-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionID',
            field=models.CharField(default='xubqtfha5cmiLYz', max_length=15, unique=True),
        ),
    ]
