# Generated by Django 3.0.6 on 2020-06-03 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanID', models.CharField(max_length=15, unique=True)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('loanAmount', models.BigIntegerField()),
                ('loanAbout', models.TextField()),
                ('loanUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
