# Generated by Django 3.0.6 on 2020-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.BooleanField(default=False),
        ),
    ]
