# Generated by Django 3.0.6 on 2020-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200511_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionID',
            field=models.CharField(default='nb5jrhIbwuklNGF', max_length=15, unique=True),
        ),
    ]
