# Generated by Django 3.0.6 on 2020-06-03 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_transaction_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=12)),
                ('nameOnCard', models.CharField(max_length=18)),
                ('expiryDate', models.DateTimeField(auto_now=True)),
                ('cvv', models.PositiveIntegerField()),
                ('pin', models.PositiveIntegerField()),
                ('cardUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
