# Generated by Django 3.0.6 on 2020-05-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200511_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionID',
            field=models.CharField(default='je4GZyD0EHvMD3C', max_length=15),
        ),
    ]
