# Generated by Django 3.0.6 on 2020-05-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200511_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionID',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
