# Generated by Django 3.0.6 on 2020-05-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200511_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accountNumber',
            field=models.CharField(default='0123456789', max_length=10),
        ),
    ]
